### ISSUE TITLE
checkpoint for TempRel inference

### ISSUE THREAD

**Issue by lashmore** [PlusLabNLP/EventPlus#3]
The TempRelAPI class references a matres_pipeline_best_hid90_dropout0.4_ew15.0.pth.tar file for the entity model. Is this checkpoint shared anywhere in particular? 

You also mention https://github.com/rujunhan/EMNLP-2019 codebase for training. Which model type did you guys use to train the above checkpoint:
1. Single task 
2. Multitask
3. Joint
4. Global

Thanks for any insight!

**Comment by ddawsari** [comment]
I'm also interested in the checkpoint, did you reach any conclusions?

Thanks

**Comment by mdkma** [comment]
Yes the checkpoint can be downloaded with [this link](https://drive.google.com/file/d/1vyeAqtDmBp98NCuEMCFvrnJ8oBuNuMr3/view?usp=sharing), I'll also add this link to the README. Thanks for reminding us about this!
